const express = require("express")
const router = express.Router()
const productController = require('../Controllers/ProductController')

router.post('/create-color', productController.createProductColor)
router.post('/create-size', productController.createProductSize)
router.post('/create-power', productController.createProductPower)
router.post('/create-product-details', productController.createProductDetails)
router.post('/create-product', productController.createProduct)
router.post('/create-product-type', productController.createProductType)
router.post('/create-product-collection', productController.createProductCollection)
// router.put('/update-product-collection/:id', productController.updateProductCollection)
// router.get('/get-all-product-collection/', productController.getAllProductCollection)
// router.delete('/delete-product-collection/:id', productController.updateProductCollection)
router.get('/get-product/:id', productController.getProduct)
router.get('/get-all-product-type', productController.getAllProductType)
router.get('/get-all', productController.getAllProduct)
router.get('/get-product-details/:id', productController.getProductDetails)
router.put('/update-product/:id', productController.updateProduct)
router.delete('/delete-product/:id', productController.deleteProduct)
router.put('/update-product-details/:id', productController.updateProductDetails)
router.delete('/delete-product-details/:id', productController.deleteProductDetails)

module.exports = router